app:
  name: TicketManager
  api:
    jwt:
      secret: ${JWT_SECRET_KEY:default_secret_key}
      issuer: TicketManagerAPI
      expiration: 604800 # 7 days in seconds
spring:
  application:
    name: TicketManager

  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
  output:
    ansi:
      enabled: always

springdoc:
  api-docs:
    path: /api-docs

logging:
  level:
    root: info
    org.springframework.web: debug
    org.springframework.web.servlet.DispatcherServlet: debug
    org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace